/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkersRouteImport } from './routes/app.workers'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppPlanningRouteImport } from './routes/app.planning'
import { Route as AppMembersRouteImport } from './routes/app.members'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppWorkersWorkerIdRouteImport } from './routes/app.workers.$workerId'
import { Route as AppEventsEventIdRouteImport } from './routes/app.events.$eventId'
import { Route as AppEventsEventIdActivityIdRouteImport } from './routes/app.events.$eventId.$activityId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkersRoute = AppWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanningRoute = AppPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkersWorkerIdRoute = AppWorkersWorkerIdRouteImport.update({
  id: '/$workerId',
  path: '/$workerId',
  getParentRoute: () => AppWorkersRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AppEventsRoute,
} as any)
const AppEventsEventIdActivityIdRoute =
  AppEventsEventIdActivityIdRouteImport.update({
    id: '/$activityId',
    path: '/$activityId',
    getParentRoute: () => AppEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/members': typeof AppMembersRoute
  '/app/planning': typeof AppPlanningRoute
  '/app/roles': typeof AppRolesRoute
  '/app/workers': typeof AppWorkersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/workers/$workerId': typeof AppWorkersWorkerIdRoute
  '/app/events/$eventId/$activityId': typeof AppEventsEventIdActivityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/members': typeof AppMembersRoute
  '/app/planning': typeof AppPlanningRoute
  '/app/roles': typeof AppRolesRoute
  '/app/workers': typeof AppWorkersRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/workers/$workerId': typeof AppWorkersWorkerIdRoute
  '/app/events/$eventId/$activityId': typeof AppEventsEventIdActivityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/members': typeof AppMembersRoute
  '/app/planning': typeof AppPlanningRoute
  '/app/roles': typeof AppRolesRoute
  '/app/workers': typeof AppWorkersRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/events/$eventId': typeof AppEventsEventIdRouteWithChildren
  '/app/workers/$workerId': typeof AppWorkersWorkerIdRoute
  '/app/events/$eventId/$activityId': typeof AppEventsEventIdActivityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/events'
    | '/app/members'
    | '/app/planning'
    | '/app/roles'
    | '/app/workers'
    | '/app/'
    | '/app/events/$eventId'
    | '/app/workers/$workerId'
    | '/app/events/$eventId/$activityId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/events'
    | '/app/members'
    | '/app/planning'
    | '/app/roles'
    | '/app/workers'
    | '/app'
    | '/app/events/$eventId'
    | '/app/workers/$workerId'
    | '/app/events/$eventId/$activityId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/events'
    | '/app/members'
    | '/app/planning'
    | '/app/roles'
    | '/app/workers'
    | '/app/'
    | '/app/events/$eventId'
    | '/app/workers/$workerId'
    | '/app/events/$eventId/$activityId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workers': {
      id: '/app/workers'
      path: '/workers'
      fullPath: '/app/workers'
      preLoaderRoute: typeof AppWorkersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planning': {
      id: '/app/planning'
      path: '/planning'
      fullPath: '/app/planning'
      preLoaderRoute: typeof AppPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workers/$workerId': {
      id: '/app/workers/$workerId'
      path: '/$workerId'
      fullPath: '/app/workers/$workerId'
      preLoaderRoute: typeof AppWorkersWorkerIdRouteImport
      parentRoute: typeof AppWorkersRoute
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppEventsRoute
    }
    '/app/events/$eventId/$activityId': {
      id: '/app/events/$eventId/$activityId'
      path: '/$activityId'
      fullPath: '/app/events/$eventId/$activityId'
      preLoaderRoute: typeof AppEventsEventIdActivityIdRouteImport
      parentRoute: typeof AppEventsEventIdRoute
    }
  }
}

interface AppEventsEventIdRouteChildren {
  AppEventsEventIdActivityIdRoute: typeof AppEventsEventIdActivityIdRoute
}

const AppEventsEventIdRouteChildren: AppEventsEventIdRouteChildren = {
  AppEventsEventIdActivityIdRoute: AppEventsEventIdActivityIdRoute,
}

const AppEventsEventIdRouteWithChildren =
  AppEventsEventIdRoute._addFileChildren(AppEventsEventIdRouteChildren)

interface AppEventsRouteChildren {
  AppEventsEventIdRoute: typeof AppEventsEventIdRouteWithChildren
}

const AppEventsRouteChildren: AppEventsRouteChildren = {
  AppEventsEventIdRoute: AppEventsEventIdRouteWithChildren,
}

const AppEventsRouteWithChildren = AppEventsRoute._addFileChildren(
  AppEventsRouteChildren,
)

interface AppWorkersRouteChildren {
  AppWorkersWorkerIdRoute: typeof AppWorkersWorkerIdRoute
}

const AppWorkersRouteChildren: AppWorkersRouteChildren = {
  AppWorkersWorkerIdRoute: AppWorkersWorkerIdRoute,
}

const AppWorkersRouteWithChildren = AppWorkersRoute._addFileChildren(
  AppWorkersRouteChildren,
)

interface AppRouteChildren {
  AppEventsRoute: typeof AppEventsRouteWithChildren
  AppMembersRoute: typeof AppMembersRoute
  AppPlanningRoute: typeof AppPlanningRoute
  AppRolesRoute: typeof AppRolesRoute
  AppWorkersRoute: typeof AppWorkersRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEventsRoute: AppEventsRouteWithChildren,
  AppMembersRoute: AppMembersRoute,
  AppPlanningRoute: AppPlanningRoute,
  AppRolesRoute: AppRolesRoute,
  AppWorkersRoute: AppWorkersRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
